// THIS IS AN AUTOGENERATED FILE PLEASE DO NOT MODIFY MANUALLY
import { IHashMapObject, ValidAdminPacket, ValidAgentPacket, ValidServerPacket } from "./ValidationTypes";

export const schemas: Record<keyof ISchema, string> = {
    ["#/definitions/IHashMapObject"]: "IHashMapObject",
    ["#/definitions/ValidAdminPacket"]: "ValidAdminPacket",
    ["#/definitions/ValidAgentPacket"]: "ValidAgentPacket",
    ["#/definitions/ValidServerPacket"]: "ValidServerPacket",
};

export interface ISchema {
    ["#/definitions/IHashMapObject"]: IHashMapObject;
    ["#/definitions/ValidAdminPacket"]: ValidAdminPacket;
    ["#/definitions/ValidAgentPacket"]: ValidAgentPacket;
    ["#/definitions/ValidServerPacket"]: ValidServerPacket;
}
