version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:296

    python3-agent:
        build:
            context: python3
            dockerfile: Dockerfile
        environment:
            - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentId&name=python3-agent
        depends_on:
            - game-server
        networks:
            - coderone-tournament

    python3-fwd:
        build:
            context: python3
            dockerfile: Dockerfile.fwd
        environment:
            - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentId&name=python3-agent
            - FWD_MODEL_CONNECTION_STRING=ws://fwd-server:6969/?role=admin
        depends_on:
            - game-server
        networks:
            - coderone-tournament
networks:
    coderone-tournament:
