version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:720
        volumes:
            - ./logs:/app/logs
            
    python3-agent:
        build:
            context: python3
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./python3:/app

    python3-fwd:
        build:
            context: python3
            dockerfile: Dockerfile.fwd

    python3-fwd-dev:
        build:
            context: python3
            dockerfile: Dockerfile.fwd.dev
        volumes:
            - ./python3:/app

    typescript-agent:
        build:
            context: typescript
            dockerfile: Dockerfile

    typescript-agent-dev:
        build:
            context: typescript
            dockerfile: Dockerfile.dev
        volumes:
            - ./typescript:/app
