version: "3"
services:
    fwd-server:
        extends:
            file: base-compose.yml
            service: game-server
        environment:
            - TELEMETRY_ENABLED=0
            - PORT=6969
        networks:
            - coderone-tournament-dev
    game-server:
        extends:
            file: base-compose.yml
            service: game-server
        ports:
            - 3000:3000
        environment:
            - PRNG_SEED=1234
            - WORLD_SEED=1234
            - TRAINING_MODE_ENABLED=0
            - TELEMETRY_ENABLED=0
            - TICK_RATE_HZ=10
            - SHUTDOWN_ON_GAME_END_ENABLED=1
        networks:
            - coderone-tournament-dev
    python3-agent:
        build:
            context: python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./python3:/app
        environment:
            - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentId&name=python3-agent
        depends_on:
            - game-server
        networks:
            - coderone-tournament-dev

    python3-fwd:
        build:
            context: python3
            dockerfile: Dockerfile.fwd.dev
        volumes:
            - ./python3:/app
        environment:
            - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentId&name=python3-agent
            - FWD_MODEL_CONNECTION_STRING=ws://fwd-server:6969/?role=admin
        depends_on:
            - game-server
        networks:
            - coderone-tournament-dev
networks:
    coderone-tournament-dev:
