import { EntityType, IGameState } from "@coderone/bomberland-library";

export const mock15x15gameState: Omit<IGameState, "connection"> = {
    game_id: "test",
    agents: { a: { agent_id: "a", unit_ids: ["c", "e", "g"] }, b: { agent_id: "b", unit_ids: ["d", "f", "h"] } },
    unit_state: {
        c: {
            coordinates: [9, 9],
            hp: 1,
            inventory: { bombs: 4 },
            blast_diameter: 3,
            unit_id: "c",
            agent_id: "a",
            stunned: 0,
            invulnerable: 723,
        },
        d: {
            coordinates: [9, 8],
            hp: 1,
            inventory: { bombs: 0 },
            blast_diameter: 3,
            unit_id: "d",
            agent_id: "b",
            stunned: 0,
            invulnerable: 139,
        },
        e: {
            coordinates: [8, 9],
            hp: 1,
            inventory: { bombs: 6 },
            blast_diameter: 5,
            unit_id: "e",
            agent_id: "a",
            stunned: 0,
            invulnerable: 719,
        },
        f: {
            coordinates: [7, 7],
            hp: 3,
            inventory: { bombs: 4 },
            blast_diameter: 5,
            unit_id: "f",
            agent_id: "b",
            stunned: 0,
            invulnerable: 0,
        },
        g: {
            coordinates: [7, 8],
            hp: 1,
            inventory: { bombs: 3 },
            blast_diameter: 3,
            unit_id: "g",
            agent_id: "a",
            stunned: 0,
            invulnerable: 715,
        },
        h: {
            coordinates: [8, 8],
            hp: 1,
            inventory: { bombs: 2 },
            blast_diameter: 3,
            unit_id: "h",
            agent_id: "b",
            stunned: 0,
            invulnerable: 260,
        },
    },
    entities: [
        { created: 0, x: 5, y: 6, type: EntityType.MetalBlock },
        { created: 0, x: 9, y: 6, type: EntityType.MetalBlock },
        { created: 0, x: 5, y: 7, type: EntityType.WoodBlock, hp: 1 },
        { created: 0, x: 9, y: 7, type: EntityType.WoodBlock, hp: 1 },
        { created: 0, x: 6, y: 7, type: EntityType.WoodBlock, hp: 1 },
        { created: 0, x: 8, y: 7, type: EntityType.WoodBlock, hp: 1 },
        { created: 300, x: 0, y: 14, type: EntityType.Blast },
        { created: 302, x: 14, y: 0, type: EntityType.Blast },
        { created: 304, x: 1, y: 14, type: EntityType.Blast },
        { created: 306, x: 13, y: 0, type: EntityType.Blast },
        { created: 308, x: 2, y: 14, type: EntityType.Blast },
        { created: 310, x: 12, y: 0, type: EntityType.Blast },
        { created: 312, x: 3, y: 14, type: EntityType.Blast },
        { created: 314, x: 11, y: 0, type: EntityType.Blast },
        { created: 316, x: 4, y: 14, type: EntityType.Blast },
        { created: 318, x: 10, y: 0, type: EntityType.Blast },
        { created: 320, x: 5, y: 14, type: EntityType.Blast },
        { created: 322, x: 9, y: 0, type: EntityType.Blast },
        { created: 324, x: 6, y: 14, type: EntityType.Blast },
        { created: 326, x: 8, y: 0, type: EntityType.Blast },
        { created: 328, x: 7, y: 14, type: EntityType.Blast },
        { created: 330, x: 7, y: 0, type: EntityType.Blast },
        { created: 332, x: 8, y: 14, type: EntityType.Blast },
        { created: 334, x: 6, y: 0, type: EntityType.Blast },
        { created: 336, x: 9, y: 14, type: EntityType.Blast },
        { created: 338, x: 5, y: 0, type: EntityType.Blast },
        { created: 340, x: 10, y: 14, type: EntityType.Blast },
        { created: 342, x: 4, y: 0, type: EntityType.Blast },
        { created: 344, x: 11, y: 14, type: EntityType.Blast },
        { created: 346, x: 3, y: 0, type: EntityType.Blast },
        { created: 348, x: 12, y: 14, type: EntityType.Blast },
        { created: 350, x: 2, y: 0, type: EntityType.Blast },
        { created: 352, x: 13, y: 14, type: EntityType.Blast },
        { created: 354, x: 1, y: 0, type: EntityType.Blast },
        { created: 356, x: 14, y: 14, type: EntityType.Blast },
        { created: 358, x: 0, y: 0, type: EntityType.Blast },
        { created: 360, x: 14, y: 13, type: EntityType.Blast },
        { created: 362, x: 0, y: 1, type: EntityType.Blast },
        { created: 364, x: 14, y: 12, type: EntityType.Blast },
        { created: 366, x: 0, y: 2, type: EntityType.Blast },
        { created: 368, x: 14, y: 11, type: EntityType.Blast },
        { created: 370, x: 0, y: 3, type: EntityType.Blast },
        { created: 372, x: 14, y: 10, type: EntityType.Blast },
        { created: 374, x: 0, y: 4, type: EntityType.Blast },
        { created: 376, x: 14, y: 9, type: EntityType.Blast },
        { created: 378, x: 0, y: 5, type: EntityType.Blast },
        { created: 380, x: 14, y: 8, type: EntityType.Blast },
        { created: 382, x: 0, y: 6, type: EntityType.Blast },
        { created: 384, x: 14, y: 7, type: EntityType.Blast },
        { created: 386, x: 0, y: 7, type: EntityType.Blast },
        { created: 388, x: 14, y: 6, type: EntityType.Blast },
        { created: 390, x: 0, y: 8, type: EntityType.Blast },
        { created: 392, x: 14, y: 5, type: EntityType.Blast },
        { created: 394, x: 0, y: 9, type: EntityType.Blast },
        { created: 396, x: 14, y: 4, type: EntityType.Blast },
        { created: 398, x: 0, y: 10, type: EntityType.Blast },
        { created: 400, x: 14, y: 3, type: EntityType.Blast },
        { created: 402, x: 0, y: 11, type: EntityType.Blast },
        { created: 404, x: 14, y: 2, type: EntityType.Blast },
        { created: 406, x: 0, y: 12, type: EntityType.Blast },
        { created: 408, x: 14, y: 1, type: EntityType.Blast },
        { created: 410, x: 0, y: 13, type: EntityType.Blast },
        { created: 412, x: 13, y: 1, type: EntityType.Blast },
        { created: 414, x: 1, y: 13, type: EntityType.Blast },
        { created: 416, x: 12, y: 1, type: EntityType.Blast },
        { created: 418, x: 2, y: 13, type: EntityType.Blast },
        { created: 420, x: 11, y: 1, type: EntityType.Blast },
        { created: 422, x: 3, y: 13, type: EntityType.Blast },
        { created: 424, x: 10, y: 1, type: EntityType.Blast },
        { created: 426, x: 4, y: 13, type: EntityType.Blast },
        { created: 428, x: 9, y: 1, type: EntityType.Blast },
        { created: 430, x: 5, y: 13, type: EntityType.Blast },
        { created: 432, x: 8, y: 1, type: EntityType.Blast },
        { created: 434, x: 6, y: 13, type: EntityType.Blast },
        { created: 436, x: 7, y: 1, type: EntityType.Blast },
        { created: 438, x: 7, y: 13, type: EntityType.Blast },
        { created: 440, x: 6, y: 1, type: EntityType.Blast },
        { created: 442, x: 8, y: 13, type: EntityType.Blast },
        { created: 444, x: 5, y: 1, type: EntityType.Blast },
        { created: 446, x: 9, y: 13, type: EntityType.Blast },
        { created: 448, x: 4, y: 1, type: EntityType.Blast },
        { created: 450, x: 10, y: 13, type: EntityType.Blast },
        { created: 452, x: 3, y: 1, type: EntityType.Blast },
        { created: 454, x: 11, y: 13, type: EntityType.Blast },
        { created: 456, x: 2, y: 1, type: EntityType.Blast },
        { created: 458, x: 12, y: 13, type: EntityType.Blast },
        { created: 460, x: 1, y: 1, type: EntityType.Blast },
        { created: 462, x: 13, y: 13, type: EntityType.Blast },
        { created: 464, x: 1, y: 2, type: EntityType.Blast },
        { created: 466, x: 13, y: 12, type: EntityType.Blast },
        { created: 468, x: 1, y: 3, type: EntityType.Blast },
        { created: 470, x: 13, y: 11, type: EntityType.Blast },
        { created: 472, x: 1, y: 4, type: EntityType.Blast },
        { created: 474, x: 13, y: 10, type: EntityType.Blast },
        { created: 476, x: 1, y: 5, type: EntityType.Blast },
        { created: 478, x: 13, y: 9, type: EntityType.Blast },
        { created: 480, x: 1, y: 6, type: EntityType.Blast },
        { created: 482, x: 13, y: 8, type: EntityType.Blast },
        { created: 484, x: 1, y: 7, type: EntityType.Blast },
        { created: 486, x: 13, y: 7, type: EntityType.Blast },
        { created: 488, x: 1, y: 8, type: EntityType.Blast },
        { created: 490, x: 13, y: 6, type: EntityType.Blast },
        { created: 492, x: 1, y: 9, type: EntityType.Blast },
        { created: 494, x: 13, y: 5, type: EntityType.Blast },
        { created: 496, x: 1, y: 10, type: EntityType.Blast },
        { created: 498, x: 13, y: 4, type: EntityType.Blast },
        { created: 500, x: 1, y: 11, type: EntityType.Blast },
        { created: 502, x: 13, y: 3, type: EntityType.Blast },
        { created: 504, x: 1, y: 12, type: EntityType.Blast },
        { created: 506, x: 13, y: 2, type: EntityType.Blast },
        { created: 508, x: 2, y: 12, type: EntityType.Blast },
        { created: 510, x: 12, y: 2, type: EntityType.Blast },
        { created: 512, x: 3, y: 12, type: EntityType.Blast },
        { created: 514, x: 11, y: 2, type: EntityType.Blast },
        { created: 516, x: 4, y: 12, type: EntityType.Blast },
        { created: 518, x: 10, y: 2, type: EntityType.Blast },
        { created: 520, x: 5, y: 12, type: EntityType.Blast },
        { created: 522, x: 9, y: 2, type: EntityType.Blast },
        { created: 524, x: 6, y: 12, type: EntityType.Blast },
        { created: 526, x: 8, y: 2, type: EntityType.Blast },
        { created: 528, x: 7, y: 12, type: EntityType.Blast },
        { created: 530, x: 7, y: 2, type: EntityType.Blast },
        { created: 532, x: 8, y: 12, type: EntityType.Blast },
        { created: 534, x: 6, y: 2, type: EntityType.Blast },
        { created: 536, x: 9, y: 12, type: EntityType.Blast },
        { created: 538, x: 5, y: 2, type: EntityType.Blast },
        { created: 540, x: 10, y: 12, type: EntityType.Blast },
        { created: 542, x: 4, y: 2, type: EntityType.Blast },
        { created: 544, x: 11, y: 12, type: EntityType.Blast },
        { created: 546, x: 3, y: 2, type: EntityType.Blast },
        { created: 548, x: 12, y: 12, type: EntityType.Blast },
        { created: 550, x: 2, y: 2, type: EntityType.Blast },
        { created: 552, x: 12, y: 11, type: EntityType.Blast },
        { created: 554, x: 2, y: 3, type: EntityType.Blast },
        { created: 556, x: 12, y: 10, type: EntityType.Blast },
        { created: 558, x: 2, y: 4, type: EntityType.Blast },
        { created: 560, x: 12, y: 9, type: EntityType.Blast },
        { created: 562, x: 2, y: 5, type: EntityType.Blast },
        { created: 564, x: 12, y: 8, type: EntityType.Blast },
        { created: 566, x: 2, y: 6, type: EntityType.Blast },
        { created: 568, x: 12, y: 7, type: EntityType.Blast },
        { created: 570, x: 2, y: 7, type: EntityType.Blast },
        { created: 572, x: 12, y: 6, type: EntityType.Blast },
        { created: 574, x: 2, y: 8, type: EntityType.Blast },
        { created: 576, x: 12, y: 5, type: EntityType.Blast },
        { created: 578, x: 2, y: 9, type: EntityType.Blast },
        { created: 580, x: 12, y: 4, type: EntityType.Blast },
        { created: 582, x: 2, y: 10, type: EntityType.Blast },
        { created: 584, x: 12, y: 3, type: EntityType.Blast },
        { created: 586, x: 2, y: 11, type: EntityType.Blast },
        { created: 588, x: 11, y: 3, type: EntityType.Blast },
        { created: 590, x: 3, y: 11, type: EntityType.Blast },
        { created: 592, x: 10, y: 3, type: EntityType.Blast },
        { created: 594, x: 4, y: 11, type: EntityType.Blast },
        { created: 596, x: 9, y: 3, type: EntityType.Blast },
        { created: 598, x: 5, y: 11, type: EntityType.Blast },
        { created: 600, x: 8, y: 3, type: EntityType.Blast },
        { created: 602, x: 6, y: 11, type: EntityType.Blast },
        { created: 604, x: 7, y: 3, type: EntityType.Blast },
        { created: 606, x: 7, y: 11, type: EntityType.Blast },
        { created: 608, x: 6, y: 3, type: EntityType.Blast },
        { created: 610, x: 8, y: 11, type: EntityType.Blast },
        { created: 612, x: 5, y: 3, type: EntityType.Blast },
        { created: 614, x: 9, y: 11, type: EntityType.Blast },
        { created: 616, x: 4, y: 3, type: EntityType.Blast },
        { created: 618, x: 10, y: 11, type: EntityType.Blast },
        { created: 620, x: 3, y: 3, type: EntityType.Blast },
        { created: 622, x: 11, y: 11, type: EntityType.Blast },
        { created: 624, x: 3, y: 4, type: EntityType.Blast },
        { created: 626, x: 11, y: 10, type: EntityType.Blast },
        { created: 628, x: 3, y: 5, type: EntityType.Blast },
        { created: 630, x: 11, y: 9, type: EntityType.Blast },
        { created: 632, x: 3, y: 6, type: EntityType.Blast },
        { created: 634, x: 11, y: 8, type: EntityType.Blast },
        { created: 636, x: 3, y: 7, type: EntityType.Blast },
        { created: 638, x: 11, y: 7, type: EntityType.Blast },
        { created: 640, x: 3, y: 8, type: EntityType.Blast },
        { created: 642, x: 11, y: 6, type: EntityType.Blast },
        { created: 644, x: 3, y: 9, type: EntityType.Blast },
        { created: 646, x: 11, y: 5, type: EntityType.Blast },
        { created: 648, x: 3, y: 10, type: EntityType.Blast },
        { created: 650, x: 11, y: 4, type: EntityType.Blast },
        { created: 652, x: 4, y: 10, type: EntityType.Blast },
        { created: 654, x: 10, y: 4, type: EntityType.Blast },
        { created: 656, x: 5, y: 10, type: EntityType.Blast },
        { created: 658, x: 9, y: 4, type: EntityType.Blast },
        { created: 660, x: 6, y: 10, type: EntityType.Blast },
        { created: 662, x: 8, y: 4, type: EntityType.Blast },
        { created: 664, x: 7, y: 10, type: EntityType.Blast },
        { created: 666, x: 7, y: 4, type: EntityType.Blast },
        { created: 668, x: 8, y: 10, type: EntityType.Blast },
        { created: 670, x: 6, y: 4, type: EntityType.Blast },
        { created: 672, x: 9, y: 10, type: EntityType.Blast },
        { created: 674, x: 5, y: 4, type: EntityType.Blast },
        { created: 676, x: 10, y: 10, type: EntityType.Blast },
        { created: 678, x: 4, y: 4, type: EntityType.Blast },
        { created: 680, x: 10, y: 9, type: EntityType.Blast },
        { created: 682, x: 4, y: 5, type: EntityType.Blast },
        { created: 684, x: 10, y: 8, type: EntityType.Blast },
        { created: 686, x: 4, y: 6, type: EntityType.Blast },
        { created: 688, x: 10, y: 7, type: EntityType.Blast },
        { created: 690, x: 4, y: 7, type: EntityType.Blast },
        { created: 692, x: 10, y: 6, type: EntityType.Blast },
        { created: 694, x: 4, y: 8, type: EntityType.Blast },
        { created: 696, x: 10, y: 5, type: EntityType.Blast },
        { created: 698, x: 4, y: 9, type: EntityType.Blast },
        { created: 700, x: 9, y: 5, type: EntityType.Blast },
        { created: 702, x: 5, y: 9, type: EntityType.Blast },
        { created: 704, x: 8, y: 5, type: EntityType.Blast },
        { created: 706, x: 6, y: 9, type: EntityType.Blast },
        { created: 708, x: 7, y: 5, type: EntityType.Blast },
        { created: 710, x: 7, y: 9, type: EntityType.Blast },
        { created: 712, x: 6, y: 5, type: EntityType.Blast },
        { created: 714, x: 8, y: 9, type: EntityType.Blast },
        { created: 716, x: 5, y: 5, type: EntityType.Blast },
        { created: 716, x: 9, y: 8, type: EntityType.Bomb, unit_id: "d", agent_id: "b", expires: 756, hp: 1, blast_diameter: 3 },
        { created: 718, x: 9, y: 9, type: EntityType.Blast },
    ],
    world: { width: 15, height: 15 },
    tick: 718,
    config: { tick_rate_hz: 10, game_duration_ticks: 300, fire_spawn_interval_ticks: 2 },
};
