FROM python:3.9.4-buster
COPY --from=coderone.azurecr.io/game-server:246 /app/game-server /app/game-server
WORKDIR /app
RUN chmod +x ./game-server
COPY ./agent_fwd_entrypoint.sh /app/entrypoint.sh
RUN chmod +x ./entrypoint.sh
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN python -m pip install -r requirements.txt
ENTRYPOINT ./entrypoint.sh

