FROM python:3-alpine
COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN python -m pip install -r requirements.txt
RUN python -m unittest
ENV PYTHONUNBUFFERED=1
ENTRYPOINT python agent_fwd.py
